# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/tamura/OneDrive/kenkyu/FPGA_tetris/Jikken2_FPGA/tetris/tetris.cache/wt [current_project]
set_property parent.project_path C:/Users/tamura/OneDrive/kenkyu/FPGA_tetris/Jikken2_FPGA/tetris/tetris.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/tamura/OneDrive/kenkyu/FPGA_tetris/Jikken2_FPGA/tetris/VGAtiming.v
  C:/Users/tamura/OneDrive/kenkyu/FPGA_tetris/Jikken2_FPGA/tetris/sound.v
  C:/Users/tamura/OneDrive/kenkyu/FPGA_tetris/Jikken2_FPGA/tetris/color.v
  C:/Users/tamura/OneDrive/kenkyu/FPGA_tetris/Jikken2_FPGA/tetris/tetris.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/tamura/OneDrive/kenkyu/FPGA_tetris/Jikken2_FPGA/tetris/basys3.xdc
set_property used_in_implementation false [get_files C:/Users/tamura/OneDrive/kenkyu/FPGA_tetris/Jikken2_FPGA/tetris/basys3.xdc]


synth_design -top tetris -part xc7a35tcpg236-1


write_checkpoint -force -noxdef tetris.dcp

catch { report_utilization -file tetris_utilization_synth.rpt -pb tetris_utilization_synth.pb }
